import { useState, useRef } from 'react';
import { resumeAPI } from '../services/api';
import type { ResumeAnalysisResponse } from '../services/api';

const ResumeAnalyzer = () => {
  const [isDragOver, setIsDragOver] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [analysisResult, setAnalysisResult] = useState<ResumeAnalysisResponse | null>(null);
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [pdfUrl, setPdfUrl] = useState<string>('');
  const [error, setError] = useState<string>('');
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
    
    const files = e.dataTransfer.files;
    if (files.length > 0) {
      handleFileSelect(files[0]);
    }
  };

  const handleFileSelect = (file: File) => {
    if (file.type !== 'application/pdf') {
      setError('Please select a PDF file only.');
      return;
    }
    
    if (file.size > 10 * 1024 * 1024) { // 10MB limit
      setError('File size must be less than 10MB.');
      return;
    }

    setError('');
    setUploadedFile(file);
    
    // Create URL for PDF preview
    const url = URL.createObjectURL(file);
    setPdfUrl(url);
    
    analyzeResume(file);
  };

  const handleFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      handleFileSelect(files[0]);
    }
  };

  const analyzeResume = async (file: File) => {
    setIsUploading(true);
    setAnalysisResult(null);
    
    try {
      const result = await resumeAPI.analyzeResume(file);
      setAnalysisResult(result);
    } catch (error: any) {
      console.error('Resume analysis failed:', error);
      if (error.response?.status === 401) {
        setError('Authentication failed. Please log in again.');
      } else if (error.response?.data?.detail) {
        setError(`Error: ${error.response.data.detail}`);
      } else {
        setError('Failed to analyze resume. Please try again.');
      }
    } finally {
      setIsUploading(false);
    }
  };

  const openFileDialog = () => {
    fileInputRef.current?.click();
  };

  const resetUpload = () => {
    setUploadedFile(null);
    setAnalysisResult(null);
    setError('');
    if (pdfUrl) {
      URL.revokeObjectURL(pdfUrl);
      setPdfUrl('');
    }
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handlePrintReport = () => {
    window.print();
  };

  const getScoreColor = (score: number) => {
    if (score >= 9) return 'text-green-400';
    if (score >= 7) return 'text-yellow-400';
    return 'text-red-400';
  };

  const getScoreBackground = (score: number) => {
    if (score >= 9) return 'bg-green-400/20';
    if (score >= 7) return 'bg-yellow-400/20';
    return 'bg-red-400/20';
  };

  return (
    <>
      {/* Print-only report section */}
      <div className="print-only">
        {analysisResult && uploadedFile && (
          <div className="max-w-4xl mx-auto p-8 bg-white text-black">
            <div className="text-center mb-8">
              <h1 className="text-3xl font-bold mb-2">Resume Analysis Report</h1>
              <p className="text-gray-600">File: {uploadedFile.name}</p>
              <p className="text-gray-600">Generated on: {new Date().toLocaleDateString()}</p>
              <p className="text-black font-bold mt-4">Generated by SCG</p>
            </div>

            {/* Overall Score */}
            <div className="text-center mb-8">
              <div className="inline-flex items-center space-x-4 bg-gray-100 rounded-lg p-4">
                <span className="text-gray-700 text-lg">Overall Score:</span>
                <div className="text-4xl font-bold text-green-600">
                  {Math.round(analysisResult.Score.reduce((a, b) => a + b, 0) / analysisResult.Score.length * 10)}%
                </div>
              </div>
            </div>

            {/* Category Scores */}
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">Score Breakdown</h2>
              <div className="space-y-4">
                {analysisResult.Category.map((category, index) => (
                  <div key={index} className="flex items-center justify-between py-2 border-b">
                    <span className="font-medium">{category}</span>
                    <span className="text-xl font-bold">{analysisResult.Score[index]}/10</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Detailed Comments */}
            <div className="space-y-6">
              <h2 className="text-2xl font-bold mb-4">Detailed Analysis & Recommendations</h2>
              {analysisResult.Category.map((category, index) => (
                <div key={index} className="mb-6">
                  <div className="flex items-center justify-between mb-2">
                    <h3 className="text-lg font-semibold">{category}</h3>
                    <span className="px-3 py-1 rounded-full text-sm font-medium bg-gray-200">
                      {analysisResult.Score[index]}/10
                    </span>
                  </div>
                  <p className="text-gray-700 leading-relaxed">
                    {analysisResult.Comments[index]}
                  </p>
                </div>
              ))}
            </div>

            {/* Footer */}
            <div className="text-center mt-12 pt-8 border-t border-gray-300">
              <p className="text-gray-500 text-sm">
                This report was generated by <strong>Sanjay Career Guidance (SCG)</strong>
              </p>
              <p className="text-gray-400 text-xs mt-1">
                Empowering careers through AI-powered insights
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Main screen content */}
      <div className="screen-only min-h-screen bg-black py-8 relative overflow-hidden">
        {/* Background animations */}
        <div className="absolute inset-0 opacity-3" style={{ filter: 'blur(2px)' }}>
          <div className="absolute inset-0 bg-grid-pattern animate-grid-move"></div>
        </div>

        <div className="absolute inset-0 pointer-events-none" style={{ filter: 'blur(100px)' }}>
          {[...Array(20)].map((_, i) => (
            <div
              key={i}
              className="absolute w-1 h-1 bg-green-400 rounded-full animate-float"
              style={{
                left: `${Math.random() * 100}%`,
                top: `${Math.random() * 100}%`,
                animationDelay: `${Math.random() * 5}s`,
                animationDuration: `${3 + Math.random() * 4}s`,
                opacity: 0.3,
              }}
            />
          ))}
        </div>

        <div className="absolute inset-0 pointer-events-none" style={{ filter: 'blur(3px)' }}>
          {[...Array(8)].map((_, i) => (
            <div
              key={i}
              className="absolute w-2 h-2 rounded-full animate-float-slow"
              style={{
                backgroundColor: '#39FF14',
                left: `${Math.random() * 100}%`,
                top: `${Math.random() * 100}%`,
                animationDelay: `${Math.random() * 8}s`,
                animationDuration: `${8 + Math.random() * 6}s`,
                opacity: 0.2,
              }}
            />
          ))}
        </div>

        <div className="absolute inset-0 pointer-events-none" style={{ filter: 'blur(5px)' }}>
          <div className="absolute top-0 left-1/4 w-px h-full bg-gradient-to-b from-transparent via-green-400 to-transparent animate-beam opacity-10"></div>
          <div className="absolute top-0 right-1/3 w-px h-full bg-gradient-to-b from-transparent via-green-400 to-transparent animate-beam-delayed opacity-10"></div>
          <div className="absolute left-0 top-1/3 w-full h-px bg-gradient-to-r from-transparent via-green-400 to-transparent animate-beam-horizontal opacity-10"></div>
        </div>

        <div className="absolute inset-0 opacity-8" style={{ filter: 'blur(4px)' }}>
          <div className="absolute top-1/4 left-1/4 w-96 h-96 rounded-full animate-pulse-glow" style={{ backgroundColor: '#39FF14', filter: 'blur(120px)' }}></div>
          <div className="absolute bottom-1/4 right-1/4 w-64 h-64 rounded-full animate-pulse-glow delay-1000" style={{ backgroundColor: '#39FF14', filter: 'blur(100px)' }}></div>
          <div className="absolute top-1/2 left-1/2 w-48 h-48 rounded-full animate-pulse-glow delay-500" style={{ backgroundColor: '#39FF14', filter: 'blur(80px)', transform: 'translate(-50%, -50%)' }}></div>
        </div>

        <div className="absolute inset-0 pointer-events-none" style={{ filter: 'blur(10px)' }}>
          <div className="absolute w-full h-px bg-gradient-to-r from-transparent via-green-400 to-transparent animate-scan opacity-15"></div>
          <div className="absolute w-full h-px bg-gradient-to-r from-transparent via-green-400 to-transparent animate-scan-reverse opacity-15" style={{ top: '60%' }}></div>
        </div>

        <div className="max-w-7xl mx-auto px-4 relative z-10">
          <div className="bg-neutral-900/40 backdrop-blur-md rounded-lg shadow-md p-6 border border-neutral-700/20">
            <h1 className="text-4xl font-bold text-white mb-4 text-center">Resume Analyzer</h1>
            <p className="text-neutral-300 text-lg mb-8 text-center">
              Get AI-powered feedback and suggestions to improve your resume
            </p>

            <div className="flex gap-6">
              {/* Left side - Upload/Results */}
              <div className={`${pdfUrl ? 'w-2/3' : 'w-full'} transition-all duration-300`}>
                {/* Upload Section - Hidden during analysis and when results are shown */}
                {!isUploading && !analysisResult && (
                  <div className="mb-8">
                    <div
                      className={`border-2 border-dashed rounded-lg p-8 text-center transition-all duration-300 cursor-pointer ${
                        isDragOver
                          ? 'border-green-400 bg-green-400/10'
                          : 'border-neutral-600/40 hover:border-green-400/50 hover:bg-green-400/5'
                      }`}
                      onDragOver={handleDragOver}
                      onDragLeave={handleDragLeave}
                      onDrop={handleDrop}
                      onClick={openFileDialog}
                    >
                      <input
                        type="file"
                        ref={fileInputRef}
                        onChange={handleFileInputChange}
                        accept=".pdf"
                        className="hidden"
                      />
                      
                      <div className="flex flex-col items-center space-y-4">
                        <div className="w-16 h-16 rounded-full bg-green-400/20 flex items-center justify-center">
                          <svg className="w-8 h-8 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                          </svg>
                        </div>
                        
                        <div>
                          <p className="text-lg font-medium text-white mb-2">
                            {isDragOver ? 'Drop your PDF here' : 'Upload your resume'}
                          </p>
                          <p className="text-neutral-400 text-sm">
                            Drag and drop your PDF file here, or click to select
                          </p>
                          <p className="text-neutral-500 text-xs mt-1">
                            PDF files only, max 10MB
                          </p>
                        </div>
                      </div>
                    </div>

                    {error && (
                      <div className="mt-4 p-4 bg-red-900/40 border border-red-500/50 rounded-lg text-red-200 text-sm">
                        {error}
                      </div>
                    )}
                  </div>
                )}

                {/* Loading State */}
                {isUploading && (
                  <div className="text-center py-16">
                    <div className="inline-flex flex-col items-center space-y-4">
                      <div className="animate-spin rounded-full h-12 w-12 border-b-2" style={{ borderColor: '#39FF14' }}></div>
                      <span className="text-neutral-300 text-lg">Analyzing your resume...</span>
                      <span className="text-neutral-500 text-sm">This may take a few moments</span>
                    </div>
                  </div>
                )}

                {/* Results Display */}
                {analysisResult && !isUploading && (
                  <div className="space-y-6">
                    {/* Overall Score */}
                    <div className="text-center mb-8">
                      <div className="inline-flex items-center space-x-4 bg-neutral-800/40 backdrop-blur-sm rounded-lg p-4">
                        <span className="text-neutral-300">Overall Score:</span>
                        <div className="text-3xl font-bold" style={{ color: '#39FF14' }}>
                          {Math.round(analysisResult.Score.reduce((a, b) => a + b, 0) / analysisResult.Score.length * 10)}%
                        </div>
                      </div>
                    </div>

                    {/* Category Scores */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
                      {analysisResult.Category.map((category, index) => (
                        <div
                          key={index}
                          className={`p-4 rounded-lg border border-neutral-600/30 ${getScoreBackground(analysisResult.Score[index])} backdrop-blur-sm`}
                        >
                          <div className="flex items-center justify-between mb-2">
                            <h3 className="font-medium text-white text-sm">{category}</h3>
                            <span className={`text-xl font-bold ${getScoreColor(analysisResult.Score[index])}`}>
                              {analysisResult.Score[index]}/10
                            </span>
                          </div>
                          <div className="w-full bg-neutral-700/50 rounded-full h-2">
                            <div
                              className="h-2 rounded-full transition-all duration-500"
                              style={{
                                width: `${(analysisResult.Score[index] / 10) * 100}%`,
                                backgroundColor: analysisResult.Score[index] >= 9 ? '#10b981' : 
                                                analysisResult.Score[index] >= 7 ? '#f59e0b' : '#ef4444'
                              }}
                            ></div>
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Detailed Comments */}
                    <div className="space-y-4">
                      <h2 className="text-2xl font-bold text-white mb-4">Detailed Analysis</h2>
                      {analysisResult.Category.map((category, index) => (
                        <div key={index} className="bg-neutral-800/40 backdrop-blur-sm rounded-lg p-6 border border-neutral-600/30">
                          <div className="flex items-center justify-between mb-3">
                            <h3 className="text-lg font-semibold text-white">{category}</h3>
                            <span className={`px-3 py-1 rounded-full text-sm font-medium ${getScoreBackground(analysisResult.Score[index])} ${getScoreColor(analysisResult.Score[index])}`}>
                              {analysisResult.Score[index]}/10
                            </span>
                          </div>
                          <p className="text-neutral-300 text-sm leading-relaxed">
                            {analysisResult.Comments[index]}
                          </p>
                        </div>
                      ))}
                    </div>

                    {/* Action Buttons */}
                    <div className="flex flex-col sm:flex-row gap-4 justify-center mt-8">
                      <button
                        onClick={resetUpload}
                        className="px-6 py-3 bg-neutral-700/40 backdrop-blur-sm text-white rounded-lg hover:bg-neutral-600/40 border border-neutral-600/30 transition-all duration-300"
                      >
                        Analyze Another Resume
                      </button>
                      <button
                        className="px-6 py-3 text-black font-medium rounded-lg transition-all duration-300 hover:scale-105"
                        style={{ 
                          backgroundColor: '#39FF14',
                          boxShadow: '0 10px 30px rgba(57, 255, 20, 0.4)'
                        }}
                        onClick={handlePrintReport}
                      >
                        Download Report
                      </button>
                    </div>
                  </div>
                )}
              </div>

              {/* Right side - PDF Preview */}
              {pdfUrl && (
                <div className="w-1/3">
                  <div className="bg-neutral-800/40 backdrop-blur-sm rounded-lg p-4 border border-neutral-600/30 h-full">
                    <h3 className="text-white font-medium mb-4 text-center">Uploaded Resume</h3>
                    <div className="bg-white rounded-lg overflow-hidden" style={{ height: '600px' }}>
                      <iframe
                        src={pdfUrl}
                        className="w-full h-full"
                        title="Resume Preview"
                      />
                    </div>
                    {uploadedFile && (
                      <p className="text-neutral-400 text-xs mt-2 text-center truncate">
                        {uploadedFile.name}
                      </p>
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ResumeAnalyzer; 